AION.Web/Models/AssignedFacilitatorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AION.Web.Models
{
    public class AssignedFacilitatorViewModel
    {
        public int ProjectId { get; set; }
        public int FacilitatorId { get; set; }
        public string FacilitatorName { get; set; }
    }
}

AION.Web/Models/ProjectDetail/AssignedReviewerListViewModel.cs
namespace AION.Web.Models.ProjectDetail
{
    public class AssignedReviewerListViewModel
    {
        public string TradeName { get; set; }
        public string ReviewerName { get; set; }
        public string DateRange { get; set; }
        public string Hours { get; set; }
    }
}

AION.Web/Models/ProjectDetail/ChangeFacilitatorModel.cs
namespace AION.Web.Models
{
    public class ChangeFacilitatorModel
    {
        public int FacilitatorId { get; set; }
        public int ProjectId { get; set; }
    }
}

AION.Web/Models/ProjectDetail/ProjectDetailViewModel.cs
using AION.BL;
using AION.BL.Models;
using AION.Manager.Models;
using AION.Web.Models.ProjectDetail;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AION.Web.Models
{
    public class ProjectDetailViewModel : ViewModelBase
    {
        private List<ProjectAudit> _projectAudits;
        private List<AuditActionRef> _auditActionRefs;
        private List<SelectListItem> _planReviewResponseSelectList;

        public ProjectDetailViewModel()
        {
            AuditLogs = new List<TableAuditLog>();
            MeetingRoomList = new List<MeetingRoom>();
            _projectAudits = new List<ProjectAudit>();
            _auditActionRefs = new List<AuditActionRef>();
        }
        public List<ProjectCycleReview> ProjectCycleReviews { get; set; } = new List<ProjectCycleReview>();
        public ProjectCycle ProjectCycle { get; set; }
        public List<PlanReviewPartialViewModel> PlanReviewViewModels { get; set; } = new List<PlanReviewPartialViewModel>();
        public PlanReviewResponseStatusEnum? PlanReviewResponseStatusSelectedEnum { get; set; }
        public int? PlanReviewResponseStatusSelected { get; set; }
        public int? PRResponse { get; set; }
        public int? FuturePRResponse { get; set; }
        public int? EMAResponse { get; set; }
        public bool RescheduleWarning { get; set; }
        public List<AuditActionRef> AuditActionRefs { get { return _auditActionRefs; } set { _auditActionRefs = value; } }
        public List<Note> Notes { get; set; }
        public List<ProjectAudit> ProjectAudits
        {
            get { return _projectAudits; }
            set
            {
                _projectAudits = value;
                if (_projectAudits != null)
                {
                    SetAuditActionRef();
                }
                else
                {
                    _projectAudits = new List<ProjectAudit>();
                }
            }
        }
        public List<TableAuditLog> AuditLogs { get; set; }
        public PlanReview PlanReview { get; set; }
        public FIFOSchedule FIFOSchedule { get; set; }
        public int Cycle { get; set; }
        public bool ProdNotKnown { get; set; }
        public bool IsAbort { get; set; }
        public DateTime? PRProdDate { get; set; }
        public DateTime? PlanReviewDate { get; set; }
        public DateTime? GateDate { get; set; }
        public List<Meeting> ScheduledMeetingList { get; set; }

        public List<SelectListItem> PlanReviewResponseSelectList
        {
            get
            {
                if (_planReviewResponseSelectList == null) BuildPlanReviewResponseSelectList();
                return _planReviewResponseSelectList;
            }
        }
        public string SelectedMeetingAction { get; set; }
        public string MeetingRoomNameSelected { get; set; }
        public List<MeetingRoom> MeetingRoomList { get; set; }
        public string ReschedulePlanReviewDisabled { get; set; } = "disabled";
        public string RescheduleExpressReviewDisabled { get; set; }
        public string AccelaProjectDeeplink { get; set; }

        /// <summary>
        /// The list of notifications for _SendNotifications modal
        /// </summary>
        public List<SendProjectNotifViewModel> ProjectNotifs { get; set; }
        public string FacilitatorName { get; internal set; }
        public List<Facilitator> FacilitatorList { get; set; }

        public Facilitator SelectedFacilitator { get; set; }

        public string CancelMeetingNotes { get; set; }

        private List<SelectListItem> _facilitatorsListViewModel;
        public List<SelectListItem> FacilitatorsListViewModel
        {
            get
            {
                if (_facilitatorsListViewModel == null)
                    _facilitatorsListViewModel = GenerateFacilitatorListViewItems();
                return _facilitatorsListViewModel;
            }
            set { _facilitatorsListViewModel = value; }
        }

        #region Private Methods
        private void SetAuditActionRef()
        {
            foreach (ProjectAudit projectaudit in _projectAudits)
            {
                projectaudit.AuditActionRef = _auditActionRefs.Where(x => x.AuditActionRefId == projectaudit.AuditActionRefId).FirstOrDefault();
            }
        }

        private void BuildPlanReviewResponseSelectList()
        {
            _planReviewResponseSelectList = new List<SelectListItem>()
            {
                 new SelectListItem() { Text = "Accept", Value = ((int)PlanReviewResponseStatusEnum.Accept).ToString()},
                 new SelectListItem() { Text = "Reject", Value = ((int)PlanReviewResponseStatusEnum.Reject).ToString()}
            };
        }

        private List<SelectListItem> GenerateFacilitatorListViewItems()
        {
            if (FacilitatorList == null)
                FacilitatorList = new List<Facilitator>();
            List<SelectListItem> ret = new List<SelectListItem>();
            ret.Add(new SelectListItem { Text = "Not Selected", Value = "-1" }); //Create a 'not Selected' item
            foreach (var item in FacilitatorList)
            {
                ret.Add(new SelectListItem { Text = item.FirstName + " " + item.LastName, Value = item.ID.ToString() });
            }
            return ret;
        }

        #endregion Private Methods
    }

}

AION.Web/Models/ProjectDetail/SendProjectNotifViewModel.cs
using AION.BL;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AION.Web.Models.ProjectDetail
{
    public class SendProjectNotifViewModel : ViewModelBase
    {
        public int ProjectNotifEmailId { get; set; }
        public DateTime SendDate { get; set; }
        public EmailNotifType EmailNotif { get; set; }
        public bool ResendAll { get; set; }
        public List<SelectListItem> Recipients { get; set; }
        public string AddRecipients { get; set; }
        public string SelectedRecipient { get; set; }
    }
}

AION.Web/Controllers/ProjectDetailController.cs
using AION.BL;
using AION.BL.Models;
using AION.Manager.Models;
using AION.Web.Helpers;
using AION.Web.Models;
using AION.Web.Models.ProjectDetail;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;

namespace AION.Web.Controllers
{
    [Authorize(Roles = "User")]
    public class ProjectDetailController : BaseProjectDetailController
    {
        public ActionResult PlanReviews(int projectId, bool canEditPlansReadyOnDate)
        {
            List<PlanReviewPartialViewModel> planReviewViewModels = GetPlanReviewsModel(projectId, canEditPlansReadyOnDate);

            return PartialView("_PlanReviews", planReviewViewModels);
        }

        public ActionResult UpdateProjectCycle(int projectId, int projectCycleId, int planReviewScheduleId, int response, string prod)
        {
            UserIdentity loggedInUser = JsonConvert.DeserializeObject<UserIdentity>(Session["LoggedInUser"].ToString());

            UpdateProjectCycleInformation(projectCycleId, planReviewScheduleId, response, prod, loggedInUser.ID, false);

            return RedirectToAction("PlanReviews", new { projectId = projectId, canEditPlansReadyOnDate = true });
        }

        public ActionResult AssignedFacilitator(int facilitatorId)
        {
            string facilitatorName = GetUserFNLM(facilitatorId);

            AssignedFacilitatorViewModel model = new AssignedFacilitatorViewModel()
            {
                FacilitatorId = facilitatorId,
                FacilitatorName = facilitatorName
            };

            return PartialView("_AssignedFacilitator", model);
        }

        public ActionResult ProjectDetail(ProjectParms projectparms)
        {
            ProjectDetailAPIHelper projectDetailAPIHelper = new ProjectDetailAPIHelper();

            ProjectDetailModel model = projectDetailAPIHelper.GetProjectDetailModel(projectparms);

            ProjectDetailViewModel vm = new ProjectDetailViewModel();

            projectparms.LoggedInUserEmail = GetLoggedInUserEmailAddress();
            vm.LoggedInUserEmail = projectparms.LoggedInUserEmail;
            if (string.IsNullOrWhiteSpace(projectparms.LoggedInUserEmail))
            {
                return RedirectToAction("Index", "Home", new { StatusMessage = "Please log in" });
            }
            else
            {
                vm.LoggedInUserEmail = projectparms.LoggedInUserEmail;
            }

            UpdateUserAndPermissions(vm);

            if (projectparms.ProjectId == null)
            {
                projectparms.StatusMessage = "Project ID is null";
                //redirect to home
                return RedirectToAction("Index", "Home", new { StatusMessage = "Project ID is null" });
            }

            //if logged in user is null then return home controller
            if (vm.LoggedInUser.ID == 0)
                return RedirectToAction("Index", "Home", new { StatusMessage = "Please log in" });

            vm.Project = model.ProjectEstimation;
            vm.Project.Notes = model.Notes;
            vm.ProjectAudits = model.ProjectAudits;
            vm.AuditActionRefs = model.AuditActionRefs;
            vm.AuditLogs = new List<TableAuditLog>();
            vm.MeetingRoomList = model.MeetingRooms;
            vm.FacilitatorList = model.Facilitators;
            vm.ProjectCycleReviews = model.ProjectCycleReviews;

            vm.PRResponse = new int?();

            vm.ProdNotKnown = vm.Project.AIONProjectStatus.ProjectStatusEnum == ProjectStatusEnum.PROD_Not_Known ? true : false;
            vm.IsAbort = vm.Project.AIONProjectStatus.ProjectStatusEnum == ProjectStatusEnum.Abort_Package ? true : false;

            vm.ScheduledMeetingList = model.ScheduledMeetings;

            //Generate deeplink to accela
            vm.AccelaProjectDeeplink = GenerateAccelaDeeplink(vm.Project.AccelaProjectRefId);

            //get the project notifications for the _SendNotifications modal
            vm.ProjectNotifs = GetProjectNotifs(model.ProjectNotificationEmails);

            bool cycleHasPROD = false;

            if (vm.ProjectCycleReviews.Count > 0)
            {
                var currentCycle = vm.ProjectCycleReviews.FirstOrDefault(x => x.ProjectCycle.CurrentCycleInd.Value == true);

                if (currentCycle != null)
                {
                    if (currentCycle.ProjectCycle.PlansReadyOnDt != null)
                    {
                        cycleHasPROD = true;
                    }

                    if (currentCycle.PlanReviews != null && currentCycle.PlanReviews.Count > 0)
                    {
                        foreach (PlanReview planReview in currentCycle.PlanReviews)
                        {
                            vm.PlanReviewDate = planReview.StartDate;

                            if (planReview.ApptResponseStatusEnum == AppointmentResponseStatusEnum.Scheduled ||
                                planReview.ApptResponseStatusEnum == AppointmentResponseStatusEnum.Tentatively_Scheduled)
                            {
                                vm.RescheduleExpressReviewDisabled = "disabled";
                            }
                        }
                    }
                }
            }

            vm.PlanReviewViewModels =
                 GetPlanReviewsModel(model.ProjectEstimation, vm.ProjectCycleReviews, vm.PermissionMapping.E_Plns_Rdy_Dt, vm.LoggedInUser);


            if (vm.PlanReviewDate.HasValue) vm.RescheduleWarning = RescheduleWarning(DateTime.Now, vm.PlanReviewDate.Value);

            // cases where Schedule Plan Review needs to be disabled
            //check project status
            if ((vm.Project.AIONProjectStatus.ProjectStatusEnum == ProjectStatusEnum.Not_Scheduled
                || vm.Project.AIONProjectStatus.ProjectStatusEnum == ProjectStatusEnum.Tentatively_Scheduled
                || vm.Project.AIONProjectStatus.ProjectStatusEnum == ProjectStatusEnum.Scheduled)
                && cycleHasPROD)
            {
                vm.ReschedulePlanReviewDisabled = "";
            }

            //check if express or prelim or cycle missing PROD
            if (vm.Project.IsProjectPreliminary
                || vm.Project.AionPropertyType == PropertyTypeEnums.Express)
            {
                vm.ReschedulePlanReviewDisabled = "disabled";
            }

            return View(vm);
        }

        [HttpPost]
        public ActionResult ChangeFacilitator(ChangeFacilitatorModel model)
        {
            // update project with new facilitator
            APIHelper apiHelper = new APIHelper();
            ProjectEstimation project = apiHelper.GetProjectDetailsByProjectId(model.ProjectId);
            project.AssignedFacilitator = model.FacilitatorId;

            if (Session["LoggedInUser"] != null)
            {
                project.UpdatedUser = JsonConvert.DeserializeObject<UserIdentity>(Session["LoggedInUser"].ToString());
            }

            bool success = ScheduleAPIHelper.UpdateAssignedFacilitator(project);

            if (success)
            {
                // return that view that will replace the Assigned Facilitator partial
                return RedirectToAction("AssignedFacilitator", new { facilitatorId = model.FacilitatorId });
            }

            return Json("There was an issue with this update.", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult UpdateAccelaFacilitator(ChangeFacilitatorModel model)
        {
            APIHelper apiHelper = new APIHelper();
            ProjectEstimation project = apiHelper.GetProjectDetailsByProjectId(model.ProjectId);
            project.AssignedFacilitator = model.FacilitatorId;

            if (project != null)
            {
                // notify Accela of facilitator change
                bool success = AccelaScheduleAPIHelper.AccelaChangeAssignedFacilitator(project);

                if (success)
                {
                    return Json("Success", JsonRequestBehavior.AllowGet);
                }
            }

            return Json("Unsuccessful", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ActionName("SubmitPrelimDateRequest")]
        public ActionResult SubmitPrelimDateRequest(RequestPrelimDatesManagerModel requestPrelimDatesManagerModel)
        {
            Helpers.APIHelper apihelper = new Helpers.APIHelper();
            apihelper.UpdatePrelimDateRequest(requestPrelimDatesManagerModel);
            return Json(new { success = true });
        }

        [HttpPost]
        [ActionName("SubmitExpressDateRequest")]
        public ActionResult SubmitExpressDateRequest(RequestExpressDatesManagerModel requestExpressDatesManagerModel)
        {
            Helpers.APIHelper apihelper = new Helpers.APIHelper();
            apihelper.UpdateExpressDateRequest(requestExpressDatesManagerModel);
            return Json(new { success = true });
        }

        [HttpPost]
        [ActionName("CancelMeeting")]
        public ActionResult CancelMeeting(CancelMeetingModel model)
        {
            if (model.AppointmentId == 0)
            {
                return Json(new { success = false });
            }

            bool cancelled = ProjectDetailAPIHelper.CancelMeetingById(model.AppointmentId, model.Notes, model.UserId);

            if (cancelled)
            {
                AccelaScheduleAPIHelper.AccelaScheduleFMA(model.AppointmentId);

                return Json(AppointmentResponseStatusDisplay.Cancelled.ToStringValue());
            }
            return null;
        }

        public bool RescheduleWarning(DateTime fromDt, DateTime toDt)
        {
            //only check for warning if a plan review date exists
            if (toDt == DateTime.MaxValue) return false;
            int diff = 0;
            foreach (DateTime day in EachDay(fromDt, toDt))
                diff++;

AION.Web/Views/ProjectDetail/ProjectDetail.cshtml
<!--#region Model & libraries-->
@using AION.Manager.Models;
@using AION.Web.Extensions
@using AION.BL
@using AION.Web.Models.Shared

@model AION.Web.Models.ProjectDetailViewModel
@{
    ViewBag.Title = "Project Details";

    bool isenabled = !Model.IsReadOnly;
    string disabledcls = Model.DisabledCls;
    string disablebtn = Model.DisabledHtml;
    string readonlytxt = Model.ReadonlyHtml;
}

<!--#endregion Model & libraries-->
<!--#region CSS-->
@section style
    {
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/ui/jquery-ui.min.css">
}

<!--#endregion CSS-->
<!--#region Hidden HTML Values-->

@Html.HiddenFor(m => m.Project.AccelaProjectRefId, Model.Project.AccelaProjectRefId)
@Html.HiddenFor(m => m.Project.ID)
@Html.HiddenFor(m => m.Project.AIONProjectStatus.ID, Model.Project.AIONProjectStatus.ID)
@Html.HiddenFor(m => m.LoggedInUser.ID, @Model.LoggedInUser.ID)
@Html.HiddenFor(m => m.LoggedInUserEmail, @Model.LoggedInUserEmail)
@Html.HiddenFor(m => m.PlanReviewDate)
@Html.HiddenFor(m => m.ProdNotKnown, new { @id = "isProdNotKnown" })
@Html.HiddenFor(m => m.IsAbort)
@Html.HiddenFor(m => m.Cycle)
@Html.HiddenFor(m => m.Project.RecIdTxt, new { @id = "recidtxt" })
@Html.Hidden("controller", System.Web.HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString())
@Html.HiddenFor(m => m.RescheduleWarning)
@*used to get the selected meeting room when opening meeting*@
@Html.Hidden("MeetingRoomRefIDSelected", new { @class = "meetingroomrefid" })

<!--#endregion Hidden HTML Values-->
<!--#region modals -->

<div class="modal fade text-left" id="dialog-modal-confirmation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel8" aria-hidden="true">
    <div class="modal-dialog modal modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-cyan white">
                <h4 class="modal-title white">
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="card-body">
                    <div class="row p-2">
                        <div class="confirmationmessage">
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-poppy" id="yes_confirmmodal">Yes</button>
                <button type="button" class="btn btn-sm btn-poppy" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade text-left" id="dialog-modal-cancel-meeting" tabindex="-1" role="dialog" aria-labelledby="myModalLabel8" aria-hidden="true">
    <div class="modal-dialog modal modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-cyan white">
                <h4 class="modal-title white">
                    Comments
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="card-body">
                    <div class="row p-2">
                        <div id="cancel-status-message" class="alert-danger" style="display:none;"></div>
                        @Html.TextAreaFor(m => m.CancelMeetingNotes, new { @class = "form-control col-md-12 h-45" }, true)
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-poppy" id="Submit_CancelMeeting">Submit</button>
                <button type="button" class="btn btn-sm btn-poppy" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade text-left" id="dialog-modal-change-facilitator" tabindex="-1" role="dialog" aria-labelledby="myModalLabel8" aria-hidden="true">
    <div class="modal-dialog modal modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-cyan white">
                <h4 class="modal-title white">
                    Facilitator
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="card-body">
                    <div class="row">
                        <div id="change-facilitator-message" class="alert-danger" style="display:none;"></div>
                        @Html.DropDownListFor(x => x.Project.AssignedFacilitator, Model.FacilitatorsListViewModel, new { @class = "form-select form-control col-md-12" })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-poppy" id="Submit_ChangeFacilitator">Submit</button>
                <button type="button" class="btn btn-sm btn-poppy" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_SendNotificationsModal", Model)


<!--#endregion modals -->

<div>
    @section breadcrumbs {
        @Html.Partial("_Breadcrumbs", Model)
    }

    <!--#region project summary  -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Project Summary</h4>
                </div>
                <div class="card-body">
                    @Html.Partial("_ProjectSummary", Model)
                </div>

            </div>
        </div>
    </div>
    <!--#endregion project summary  -->
    <!--#region Meetings-->
    <div class="card mb-4 meetings">
        @if (Model != null)
        {
            <div class="card-header font-weight-bold"><h4 class="card-title">Meetings</h4></div>
            <div class="card-body">
                <div class="d-flex">
                    <div>
                        @Html.Partial("_Meetings", Model)
                        <input type="hidden" id="appointmentId" name="appointmentId" />
                    </div>
                </div>
            </div>
        }
    </div>
    <!--#endregion Meetings-->
    <!--#region Act on Behalf of Customer-->
    <div class="card mb-4">
        <div class="card-header font-weight-bold"><h4 class="card-title">Act on Behalf of Customer</h4></div>
        <div class="card-body">
            <div class="d-flex">
                <div>
                    <div id="planReviews">
                        @Html.Partial("_PlanReviews", Model.PlanReviewViewModels)
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--#endregion Act on Behalf of Customer-->
    <!--#region History-->
    <div class="card mb-4" id="projectAudits">
        @if (Model != null)
        {
            <div class="card-content collapse show">
                <div class="card-header font-weight-bold"><h4 class="card-title">History </h4></div>
                <div class="card-body card-dashboard">
                    @Html.Partial("_ProjectAudit", Model.ProjectAudits)
                </div>
            </div>
        }
    </div>
    <!--#endregion History  -->
</div>

<!--#region Scripts  -->
@section scripts{
    <script src="~/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="~/app-assets/js/scripts/pages/project-detail/project-detail.js"></script>
    <script type="text/javascript" src="~/app-assets/js/scripts/pages/project-detail/send-notifs.js"></script>
    <script type="text/javascript" src="~/app-assets/js/scripts/pages/project-detail/update-project-cycle.js"></script>
}

<!--#endregion Scripts  -->

AION.Web/Views/ProjectDetail/_AssignedFacilitator.cshtml
@model AION.Web.Models.AssignedFacilitatorViewModel

@Model.FacilitatorName <a class="change-facilitator" data-toggle="modal" data-target="#dialog-modal-change-facilitator" style="text-decoration:underline;margin-left:10px;" href="#" data-id=@Model.FacilitatorId>change facilitator</a>

AION.Web/Views/ProjectDetail/_PlanReviews.cshtml
@model List<AION.Web.Models.PlanReviewPartialViewModel>



<table class="table table-striped table-bordered zero-configuration dataTable" id="planreviews">
    <thead class="card-header">
        <tr>
            <th>Plan Review Date</th>
            <th>Status</th>
            <th>Cycle</th>
            <th>Plans Ready On Date</th>
            <th></th>
            <th></th>
            <th>Plan Reviewers</th>
        </tr>
    </thead>
    <tbody class="card-body">
        @foreach (var planReview in Model)
        {
            if (planReview.IsCurrentCycle == false && planReview.IsFutureCycle == false)
            {
                @Html.Partial("~/Views/Shared/ProjectDetails/_PlanReviewNotEditable.cshtml", planReview)
            }
            else
            {
                if (planReview.IsFifoProject)
                {
                    @Html.Partial("~/Views/Shared/ProjectDetails/_FifoPlanReviewEditable.cshtml", planReview)
                }
                else
                {
                    @Html.Partial("~/Views/Shared/ProjectDetails/_PlanReviewEditable.cshtml", planReview)

                }
            }

        }
    </tbody>
</table>

AION.Web/Views/ProjectDetail/_ProjectSummary.cshtml
@model AION.Web.Models.ProjectDetailViewModel


@{
    bool isFIFOProject = Model.Project.IsFifo;
}
<div class="row">
    <div class="col-md-4">
        <label class="text-bold-600">Project # :</label>
        <label>@Model.Project.AccelaProjectRefId</label>
    </div>
    <div class="col-md-4">
        <!--<label class="text-bold-600">-->@*Project Status :*@<!--</label>-->
        <label id="projectStatus">@Html.Partial("_ProjectStatusLabel", Model.Project.AIONProjectStatus.ProjectStatusEnum)</label>
    </div>
    <div class="col-md-4">
        <label class="text-bold-600">Gate Date :</label>
        <label id="projectStatus">@(Model.Project.GateDt == null ? string.Empty : ((DateTime)Model.Project.GateDt).ToShortDateString())</label>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <label class="text-bold-600">Project Name :</label>
        <label>@Model.Project.ProjectName</label>
    </div>
    <div class="col-md-4">
        <label class="text-bold-600">Project Type :</label>
        <label>@Model.Project.AccelaPropertyType.ToStringValue()</label>
    </div>
    <div class="col-md-4">
        <label class="text-bold-600">Project Level :</label>
        <label>@Model.Project.ProjectLvlTxt</label>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <label class="text-bold-600">Project Address :</label>
        <label>@Model.Project.ProjectAddress</label>
    </div>
    <div class="col-md-4">
        <label class="text-bold-600">Building Code Version :</label>
        <label>@Model.Project.DisplayOnlyInformation.BuildingCodeVersion</label>
     </div>
     @{ if (isFIFOProject)
            {
         <div class="col-md-4">
             <label class="text-bold-600">FIFO Due Dt :</label>
             <label> @(Model.Project.FifoDueAccelaDt == null ? string.Empty : ((DateTime)Model.Project.FifoDueAccelaDt).ToShortDateString())</label>
         </div>
            }
        }
</div>

<div class="row">

    <div class="col-md-4">
        <label class="text-bold-600">Team Score :</label>
        <label>@Model.Project.TeamGradeTxt</label>
    </div>

    <div class="col-md-4">
        <label class="text-bold-600">Facilitator :</label>
        <label>
            <span id="facilitatorPartial">
                @{ Html.RenderAction("AssignedFacilitator", "ProjectDetail", new
                    {
                        projectId = Model.Project.ID,
                        facilitatorId = Model.Project.AssignedFacilitator,
                    });}
            </span>
        </label>
    </div>
    @{ if (Model.Project.IsProjectRTAP)
        {
            <div class="col-md-4">
                <label class="text-bold-600">Original Project # :</label>
                <label>@Model.Project.AccelaRTAPProjectRefId</label>
            </div>
        }
    }
</div>